In [2]:
import numpy as np


In [2]:
arr1 = [1,24,44,23,54]
arr2 = [23,46,76,65,53]


In [3]:
arr1 + arr2

[1, 24, 44, 23, 54, 23, 46, 76, 65, 53]

In [4]:
new = np.array(arr1)
old = np.array(arr2)

new + old

array([ 24,  70, 120,  88, 107])

In [ ]:
new.shape #for size of an arr

(5,)

In [ ]:
new.ndim              #for dimn. of arr

1

In [11]:
new.mean()

np.float64(29.2)

In [13]:
new.max()

np.int64(54)

In [14]:
new.argmax()

np.int64(4)

In [ ]:
np.random.permutation(new.size)         #random num import import krne liye

array([1, 0, 3, 2, 4], dtype=int32)

In [16]:
np.random.permutation(new.size)

array([1, 0, 4, 2, 3], dtype=int32)

In [18]:
ages = [21,43,54,25,53]
name = ["A1", "A2", "A3", "A4", "A5"]

ages = np.array(ages)
name = np.array(name)

ages.argsort()

array([0, 3, 1, 4, 2])

In [19]:
name[ages.argsort()]

array(['A1', 'A4', 'A2', 'A5', 'A3'], dtype='<U2')

In [4]:
np.random.randint(10,50)

15

In [5]:
np.random.randint(10,50,3)

array([27, 10, 18], dtype=int32)

In [6]:
np.random.seed(7)
np.random.permutation(6)

array([3, 5, 0, 2, 1, 4], dtype=int32)